### ISSUE TITLE
Indent guides off on empty lines

### ISSUE THREAD

**Issue by chris-scheurle** [thomhines/tonights-specials#1]
On my install (OS X 10.10.5 / Brackets 1.5.0-16538), [lkcampbell](http://github.com/lkcampbell) / **[brackets-indent-guides](http://github.com/lkcampbell/brackets-indent-guides)** are off by a few pixels, on empty lines:

> ![Screenshot](http://demos.scheurle.info/screenshots/20151127043421.png)

I got this fixed using [tobibeer](http://github.com/tobibeer) / **[brackets-custom-css](http://github.com/tobibeer/brackets-custom-css)** and:

``` css
#editor-holder .CodeMirror pre{
    padding-left: 0;
}
```

Maybee you want to take a closer look? :smile:

**Comment by thomhines** [comment]
Hey, thanks for trying out this theme! And thanks for sending the snippet of CSS.

Strange... I've got the same setup as you and I'm not getting that indentation, or that yellowish bar to the left of the gutter. Is that perhaps coming from another plugin? I added your code to my theme and it didn't have any negative effects, so I went ahead and left it in.

The extension registry is giving me troubles when I try to upload, but you can install the update from github. I hope that fixes it for you!

**Comment by chris-scheurle** [comment]
I'm glad I could be of help. :smile: ... though the problem seems to persist. :confused:

I took a look at your code and what I don't understand: in the line right above the new fix, you are *adding* exactly said `7px`to the editor view ... 
```less
// Add padding to left side of code lines
.CodeMirror pre {
	padding: 0 15px 0 7px;
}

// Remove small bit of space on some people's editors
#editor-holder .CodeMirror pre{
	padding-left: 0px;
}
```
So maybee the problem is not the padding beeing *added* but on *some* lines beeing *removed* by some other plugin?

The yellow ( / green / red) bars are inserted by [zaggino](http://github.com/zaggino) / [**brackets-git**](http://github.com/zaggino/brackets-git) (marking up lines of code that changed / got added / were removed since the last GIT commit).

**Comment by chris-scheurle** [comment]
I'm glad I could be of help. :smile: 

The yellow ( / green / red) bars are inserted by [zaggino](http://github.com/zaggino) / [**brackets-git**](http://github.com/zaggino/brackets-git) (marking up lines of code that changed / got added / were removed since the last GIT commit).

**Comment by chris-scheurle** [comment]
I'm glad I could be of help. :smile: ... though your fix doesn't seem to _fix_ anything. :cry:

I took a closer look at your code and it seems, you are inserting the `7px` padding _yourself_ (in the line just above the new fix):

``` less
// Add padding to left side of code lines
.CodeMirror pre {
    padding: 0 15px 0 7px;
}

// Remove small bit of space on some people's editors
#editor-holder .CodeMirror pre{
    padding-left: 0px;
}
```

So, maybe the problem is not the space beeing _added_, but on _some_ lines beeing _removed_ by some plugin? :confused:

The yellow ( / green / red) bars are inserted by [zaggino](http://github.com/zaggino) / [**brackets-git**](http://github.com/zaggino/brackets-git) (marking up lines of code that changed / got added / were removed since the last GIT commit).
